services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user_service
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - user_service

volumes:
  db_data:

networks:
  user_service:
    driver: bridge
    name: user_service